[tool.poetry]
name = "baseapi"
version = "0.1.8"
description = ""
authors = ["Luke Hodkinson <furious.luke@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.27.0"
requests-toolbelt = "^1.0.0"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
pytest = "^7.2"
