[tool.poetry]
name = "baseapi"
version = "0.1.2"
description = ""
authors = ["Luke Hodkinson <furious.luke@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.5"
requests = "^2.24.0"
requests-toolbelt = "^0.9.1"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
pytest = "^6.1.0"
