[tool.poetry]
name = "baseapi"
version = "0.1.6"
description = ""
authors = ["Luke Hodkinson <furious.luke@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.27.0"
requests-toolbelt = "^0.9.1"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
pytest = "^6.2.5"
